default_platform(:android)

platform :android do

  desc "build"
  lane :build do
    gradle(
        task: 'assembleRelease',
        properties: {
                 "android.injected.signing.store.file" => "/home/runner/keystore",
                 "android.injected.signing.store.password" => "password",
                 "android.injected.signing.key.alias" => "key0",
                 "android.injected.signing.key.password" => "password",
                 "android.injected.version.code" => ENV["VERSION_CODE"],
                 "android.injected.version.name" => ENV["VERSION_NAME"]
               }
    )
  end

  lane :deploy do
      upload_to_play_store(track: 'internal')
  end
end
