default_platform(:android)

platform :android do

  desc "build"
  lane :build do
    android_set_version_name(
        version_name: ENV["VERSION_NAME"],
        gradle_file: "app/build.gradle.kts"
    )
    android_set_version_name(
        version_code: ENV["VERSION_CODE"],
        gradle_file: "app/build.gradle.kts"
    )

    gradle(
        task: 'assembleRelease',
        properties: {
                 "android.injected.signing.store.file" => "/home/runner/keystore",
                 "android.injected.signing.store.password" => "password",
                 "android.injected.signing.key.alias" => "key0",
                 "android.injected.signing.key.password" => "password",
               }
    )
  end

  lena :deploy do
      upload_to_play_store(track: 'internal')
  end
end
